name = "subtitle-translator"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
# 使用 @cloudflare/next-on-pages 构建输出
# 注意: Pages 项目不支持在 wrangler.toml 中配置 build 命令
# 请在 Cloudflare Dashboard 的 Build settings 中设置 "npm run pages:build"
pages_build_output_dir = ".vercel/output/static"
