name = "subtitle-translator"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 输出目录
# OpenNext 生成 worker.js 和 assets，我们将其转换为 Pages Advanced Mode 格式
pages_build_output_dir = ".open-next/worker"
