name = "subtitle-translator"
compatibility_date = "2024-12-15"

[build]
command = "npx @cloudflare/next-on-pages@1"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

[pages_build_output_dir]
value = ".vercel/output/static" 